=== DimaLuchyk/processController/WinProcessController/WinProcessController/ETTestClient/FarmConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2015 sp2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="IP">
    <xs:simpleType>
      <xs:restriction base="xs:string">
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="ETR">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="IP"/>
        <xs:element ref="IsSim"/>
        <xs:element ref="ManifestLocation"/>
        <xs:element ref="HasTestAgent"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Max" type="xs:short"/>
  <xs:element name="Min" type="xs:short"/>
  <xs:element name="Band">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ranges"/>
      </xs:sequence>
      <xs:attribute name="Name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Enabled" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:boolean">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="ETRs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ETR" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name">
    <xs:simpleType>
      <xs:restriction base="xs:string">
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ranges" />
      </xs:sequence>
      <xs:attribute name="Prefix" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Format" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="AdmitOk" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Ignore" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Subscribe" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Beds">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Group" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Unit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Facility"/>
        <xs:element ref="Name"/>
        <xs:element ref="SupportedPatientType"/>
        <xs:element ref="Beds" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Bands">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Band" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="IsSim">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="False"/>
        <xs:enumeration value="True"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Names">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MaleFirstNames"/>
        <xs:element ref="FemaleFirstNames"/>
        <xs:element ref="Surnames"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Range">
    <xs:complexType>
      <xs:attribute name="Start" type="xs:short" use="required"/>
      <xs:attribute name="End" type="xs:short" use="required"/>
      <xs:attribute name="Increment" type="xs:byte" use="optional" default="1"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Units">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Unit" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Ranges">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Range" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Facility">
    <xs:simpleType>
      <xs:restriction base="xs:string">
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="IgnoreSims" default="True">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="AutoSubscribe"  default="False">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="AutoGetDeviceInfo" default="True"  >
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="AutoGetPatientInfo" default="False">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="EnableMetrics"  default="True"  >
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Surnames">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FarmConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ETRs"/>
        <xs:element ref="Facility"/>
        <xs:element ref="IgnoreSims" minOccurs="0" />
        <xs:element ref="AutoSubscribe" minOccurs="0" />
        <xs:element ref="AutoGetDevice" minOccurs="0" />
        <xs:element ref="AutoGetPatient" minOccurs="0" />
        <xs:element ref="EnableMetrics" minOccurs="0" />
        <xs:element ref="Transmitters"/>
        <xs:element ref="Units"/>
        <xs:element ref="PatientTTL"/>
        <xs:element ref="AdmitDischargeInterval"/>
        <xs:element ref="UseDeviceViews"/>
        <xs:element ref="Names"/>
        <xs:element ref="GlobalTestParams"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PatientTTL">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Min"/>
        <xs:element ref="Max"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AdmitDischargeInterval">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Min"/>
        <xs:element ref="Max"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="UseDeviceViews">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="HasTestAgent">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="True"/>
        <xs:enumeration value="False"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Transmitters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Bands"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MaleFirstNames">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FemaleFirstNames">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GlobalTestParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="DischargeAllAtTestEnd"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ManifestLocation" type="xs:anyURI"/>
  <xs:element name="SupportedPatientType">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Adult"/>
        <xs:enumeration value="Neonate"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="DischargeAllAtTestEnd" type="xs:boolean"/>
</xs:schema>


=== DimaLuchyk/processController/WinProcessController/WinProcessController/ETTestClient/FarmConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<FarmConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FarmConfig.xsd">
  <ETRs>
    <ETR>
      <IP>172.24.197.130</IP>
      <IsSim>True</IsSim>
      <ManifestLocation>C:\ProgramFiles\Spacelabs\ET</ManifestLocation>
      <HasTestAgent>False</HasTestAgent>
    </ETR>
	<ETR>
      <IP>172.24.197.87</IP>
      <IsSim>True</IsSim>
      <ManifestLocation>C:\ProgramFiles\Spacelabs\ET</ManifestLocation>
      <HasTestAgent>False</HasTestAgent>
    </ETR>
  </ETRs>
  <Facility>Facility1</Facility>
  <IgnoreSims>False</IgnoreSims>
  <AutoSubscribe>True</AutoSubscribe>
  <AutoGetDeviceInfo>True</AutoGetDeviceInfo>
  <AutoGetPatientInfo>False</AutoGetPatientInfo>
  <!--NOTE to completely disable metrics collection also change WpfETTestClient.exe.config -->
  <EnableMetrics>False</EnableMetrics>
  <Transmitters>
    <Bands>
      <Band Name="QLive Narrow" Enabled="true">
        <Ranges>
          <Range Start="1352" End="1480" Increment="1" />
        </Ranges>
      </Band>
    </Bands>
  </Transmitters>
  <Units>
    <Unit>
      <Facility>Facility1</Facility>
      <Name>Unit1</Name>
      <SupportedPatientType>Adult</SupportedPatientType>
      <Beds>
        <Group Prefix="Bd" Format="D3" AdmitOk="true" Ignore="false" Subscribe="true">
          <Ranges>
            <Range Start="1" End="99" />
          </Ranges>
        </Group>
      </Beds>
    </Unit>
  </Units>
  <PatientTTL>
    <!--Patient Time to Live is minimum time before a patient will be discharged (secs)-->
    <Min>20</Min>
    <Max>40</Max>
  </PatientTTL>
  <AdmitDischargeLoop>
    <Iterations>10000</Iterations>
    <DischargeRandomPatient>true</DischargeRandomPatient>
    <AdmitDischargeInterval>
      <Min>10</Min>
      <Max>10</Max>
    </AdmitDischargeInterval>
  </AdmitDischargeLoop>
  <UseDeviceViews>True</UseDeviceViews>
  <Names>
    <MaleFirstNames>
      <Name>Jacob</Name>
      <Name>Jonah</Name>
      <Name>Shawn</Name>
      <Name>Aaron</Name>
      <Name>Liam</Name>
      <Name>Daniel</Name>
      <Name>Ryan</Name>
      <Name>James</Name>
      <Name>Ethan</Name>
      <Name>Harry</Name>
      <Name>David</Name>
      <Name>Luke</Name>
      <Name>Alex</Name>
      <Name>Matthew</Name>
      <Name>Tyler</Name>
      <Name>Jack</Name>
      <Name>Joshua</Name>
      <Name>Niall</Name>
      <Name>Michael</Name>
      <Name>Andrew</Name>
      <Name>Alexander</Name>
      <Name>Noah</Name>
      <Name>Dylan</Name>
      <Name>Zayn</Name>
      <Name>Jordan</Name>
      <Name>Spencer</Name>
      <Name>Adam</Name>
      <Name>Austin</Name>
      <Name>Nathan</Name>
      <Name>Aiden</Name>
      <Name>Logan</Name>
      <Name>Kevin</Name>
      <Name>Jayden</Name>
      <Name>Christopher</Name>
      <Name>Anthony</Name>
      <Name>John</Name>
      <Name>Mason</Name>
      <Name>Jackson</Name>
      <Name>Justin</Name>
      <Name>Brian</Name>
      <Name>Louis</Name>
      <Name>William</Name>
      <Name>Jason</Name>
      <Name>Blake</Name>
      <Name>Brandon</Name>
      <Name>Kyle</Name>
      <Name>Max</Name>
      <Name>Isaac</Name>
      <Name>Benjamin</Name>
      <Name>Ian</Name>
    </MaleFirstNames>
    <FemaleFirstNames>
      <Name>Sophia</Name>
      <Name>Emma</Name>
      <Name>Olivia</Name>
      <Name>Isabella</Name>
      <Name>Ava</Name>
      <Name>Mia</Name>
      <Name>Emily</Name>
      <Name>Abigail</Name>
      <Name>Madison</Name>
      <Name>Elizabeth</Name>
      <Name>Charlotte</Name>
      <Name>Avery</Name>
      <Name>Sofia</Name>
      <Name>Chloe</Name>
      <Name>Ella</Name>
      <Name>Harper</Name>
      <Name>Amelia</Name>
      <Name>Aubrey</Name>
      <Name>Addison</Name>
      <Name>Evelyn</Name>
      <Name>Natalie</Name>
      <Name>Grace</Name>
      <Name>Hannah</Name>
      <Name>Zoey</Name>
      <Name>Victoria</Name>
      <Name>Lillian</Name>
      <Name>Lily</Name>
      <Name>Brooklyn</Name>
      <Name>Samantha</Name>
      <Name>Layla</Name>
      <Name>Zoe</Name>
      <Name>Audrey</Name>
      <Name>Leah</Name>
      <Name>Allison</Name>
      <Name>Anna</Name>
      <Name>Aaliyah</Name>
      <Name>Savannah</Name>
      <Name>Gabriella</Name>
      <Name>Camila</Name>
      <Name>Aria</Name>
      <Name>Kaylee</Name>
      <Name>Scarlett</Name>
      <Name>Hailey</Name>
      <Name>Arianna</Name>
      <Name>Riley</Name>
      <Name>Alexis</Name>
      <Name>Nevaeh</Name>
      <Name>Sarah</Name>
      <Name>Claire</Name>
      <Name>Sadie</Name>
      <Name>Peyton</Name>
      <Name>Aubree</Name>
      <Name>Serenity</Name>
      <Name>Ariana</Name>
      <Name>Genesis</Name>
      <Name>Penelope</Name>
      <Name>Alyssa</Name>
      <Name>Bella</Name>
      <Name>Taylor</Name>
      <Name>Alexa</Name>
      <Name>Kylie</Name>
      <Name>Mackenzie</Name>
      <Name>Caroline</Name>
      <Name>Kennedy</Name>
      <Name>Autumn</Name>
      <Name>Lucy</Name>
      <Name>Ashley</Name>
      <Name>Madelyn</Name>
    </FemaleFirstNames>
    <Surnames>
      <Name>Smith</Name>
      <Name>Johnson</Name>
      <Name>Williams</Name>
      <Name>Jones</Name>
      <Name>Brown</Name>
      <Name>Davis</Name>
      <Name>Miller</Name>
      <Name>Wilson</Name>
      <Name>Moore</Name>
      <Name>Taylor</Name>
      <Name>Anderson</Name>
      <Name>Thomas</Name>
      <Name>Jackson</Name>
      <Name>White</Name>
      <Name>Harris</Name>
      <Name>Martin</Name>
      <Name>Thompson</Name>
      <Name>Garcia</Name>
      <Name>Martinez</Name>
      <Name>Robinson</Name>
      <Name>Clark</Name>
      <Name>Rodriguez</Name>
      <Name>Lewis</Name>
      <Name>Lee</Name>
      <Name>Walker</Name>
      <Name>Hall</Name>
      <Name>Allen</Name>
      <Name>Young</Name>
      <Name>Hernandez</Name>
      <Name>King</Name>
      <Name>Wright</Name>
      <Name>Lopez</Name>
      <Name>Hill</Name>
      <Name>Scott</Name>
      <Name>Green</Name>
      <Name>Adams</Name>
      <Name>Baker</Name>
      <Name>Gonzalez</Name>
      <Name>Nelson</Name>
      <Name>Carter</Name>
      <Name>Mitchell</Name>
      <Name>Perez</Name>
      <Name>Roberts</Name>
      <Name>Turner</Name>
      <Name>Phillips</Name>
      <Name>Campbell</Name>
      <Name>Parker</Name>
      <Name>Evans</Name>
      <Name>Edwards</Name>
      <Name>Collins</Name>
      <Name>Stewart</Name>
      <Name>Sanchez</Name>
      <Name>Morris</Name>
      <Name>Rogers</Name>
      <Name>Reed</Name>
      <Name>Cook</Name>
      <Name>Morgan</Name>
      <Name>Bell</Name>
      <Name>Murphy</Name>
      <Name>Bailey</Name>
      <Name>Rivera</Name>
      <Name>Cooper</Name>
      <Name>Richardson</Name>
      <Name>Cox</Name>
      <Name>Howard</Name>
      <Name>Ward</Name>
      <Name>Torres</Name>
      <Name>Peterson</Name>
      <Name>Gray</Name>
      <Name>Ramirez</Name>
      <Name>James</Name>
      <Name>Watson</Name>
      <Name>Brooks</Name>
      <Name>Kelly</Name>
      <Name>Sanders</Name>
      <Name>Price</Name>
      <Name>Bennett</Name>
      <Name>Wood</Name>
      <Name>Barnes</Name>
      <Name>Ross</Name>
      <Name>Henderson</Name>
      <Name>Coleman</Name>
      <Name>Jenkins</Name>
      <Name>Perry</Name>
      <Name>Powell</Name>
      <Name>Long</Name>
      <Name>Patterson</Name>
      <Name>Hughes</Name>
      <Name>Flores</Name>
      <Name>Washington</Name>
      <Name>Butler</Name>
      <Name>Simmons</Name>
      <Name>Foster</Name>
      <Name>Gonzales</Name>
      <Name>Bryant</Name>
      <Name>Alexander</Name>
      <Name>Russell</Name>
      <Name>Griffin</Name>
      <Name>Diaz</Name>
      <Name>Hayes</Name>
    </Surnames>
  </Names>
  <GlobalTestParams>
    <DischargeAllAtTestEnd>false</DischargeAllAtTestEnd>
  </GlobalTestParams>
</FarmConfig>
